{% set name = "tilematrix" %}
{% set version = "2022.11.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tilematrix-{{ version }}.tar.gz
  sha256: b70960ccbd209b0ff0ca14199a7f7c721f1705ee13d4e998a07eca825fde56f5

build:
  entry_points:
    - tmx=tilematrix.tmx.main:tmx
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pytest-runner
    - pip
  run:
    - python >=3.6
    - affine
    - click
    - geojson
    - rasterio >=1.0.21
    - shapely

test:
  imports:
    - tilematrix
  commands:
    - pip check
    - tmx --help
  requires:
    - pip

about:
  home: https://github.com/ungarj/tilematrix
  summary: helps handling tile pyramids
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ungarj
    - Scartography
